name: Build and Upload EXE

on:
  schedule:
    - cron: "0 0 * * 0" # Uruchamianie raz w tygodniu w niedzielę o północy (UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Ustaw wersję Pythona zgodnie z wymaganiami projektu

      - name: Install dependencies
        run: .\skrypt.ps1

      - name: Build EXE
        run: pyinstaller --onefile --noconsole gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gui_exe
          path: dist\gui.exe
